/* eslint-disable @typescript-eslint/no-explicit-any -- Supabase generated types don't yet include new tables (regenerated by Cloud after migration). */
import { createServerFn } from "@tanstack/react-start";
import { requireSupabaseAuth } from "@/integrations/supabase/auth-middleware";
import {
  computeDurationMinutes,
  computeDisplacementCents,
  computeSubtotalCents,
  computeTotals,
} from "@/lib/serviceOrders/finance";
import type {
  DisplacementInput,
  FinalizeOrderInput,
  LaborEntry,
  LaborEntryInput,
  OrderFinancials,
} from "@/types/financials";

const LABOR_SELECT = `
  id, service_order_id, technician_id, role, work_date, start_time, end_time,
  duration_minutes, hourly_rate_cents, subtotal_cents, description,
  technician:technicians(id, full_name, role)
`;

const TECHNICIAN_HISTORY_SELECT = `
  id, service_order_id, technician_id, role, work_date, start_time, end_time,
  duration_minutes, hourly_rate_cents, subtotal_cents, description,
  service_order:service_orders!service_order_labor_entries_service_order_id_fkey(
    id, number, title, status, opened_at, started_at, finished_at, closed_at,
    service_type, service_type_other,
    client:clients!service_orders_client_id_fkey(id, name, unit),
    client_unit:client_units!service_orders_client_unit_id_fkey(id, name, sector, city, state)
  )
`;

export type TechnicianLaborHistoryRow = {
  id: string;
  service_order_id: string;
  technician_id: string | null;
  role: string | null;
  work_date: string;
  start_time: string;
  end_time: string;
  duration_minutes: number;
  hourly_rate_cents: number;
  subtotal_cents: number;
  description: string | null;
  service_order: {
    id: string;
    number: number;
    title: string;
    status: string;
    opened_at: string;
    started_at: string | null;
    finished_at: string | null;
    closed_at: string | null;
    service_type: string | null;
    service_type_other: string | null;
    client: { id: string; name: string; unit: string | null } | null;
    client_unit: {
      id: string;
      name: string;
      sector: string | null;
      city: string | null;
      state: string | null;
    } | null;
  } | null;
};

function normalizeLabor(row: any): LaborEntry {
  return {
    id: row.id,
    service_order_id: row.service_order_id,
    technician_id: row.technician_id ?? null,
    role: row.role ?? null,
    work_date: row.work_date,
    start_time: row.start_time,
    end_time: row.end_time,
    duration_minutes: row.duration_minutes ?? 0,
    hourly_rate_cents: row.hourly_rate_cents ?? 0,
    subtotal_cents: row.subtotal_cents ?? 0,
    description: row.description ?? null,
    technician: row.technician
      ? {
          id: row.technician.id,
          full_name: row.technician.full_name,
          role: row.technician.role ?? null,
        }
      : null,
  };
}

function normalizeTechnicianHistory(row: any): TechnicianLaborHistoryRow {
  return {
    id: row.id,
    service_order_id: row.service_order_id,
    technician_id: row.technician_id ?? null,
    role: row.role ?? null,
    work_date: row.work_date,
    start_time: row.start_time,
    end_time: row.end_time,
    duration_minutes: row.duration_minutes ?? 0,
    hourly_rate_cents: row.hourly_rate_cents ?? 0,
    subtotal_cents: row.subtotal_cents ?? 0,
    description: row.description ?? null,
    service_order: row.service_order
      ? {
          id: row.service_order.id,
          number: row.service_order.number,
          title: row.service_order.title,
          status: row.service_order.status,
          opened_at: row.service_order.opened_at,
          started_at: row.service_order.started_at ?? null,
          finished_at: row.service_order.finished_at ?? null,
          closed_at: row.service_order.closed_at ?? null,
          service_type: row.service_order.service_type ?? null,
          service_type_other: row.service_order.service_type_other ?? null,
          client: row.service_order.client ?? null,
          client_unit: row.service_order.client_unit ?? null,
        }
      : null,
  };
}

function normalizeFinancials(row: any): OrderFinancials | null {
  if (!row) return null;
  return {
    service_order_id: row.service_order_id,
    total_labor_minutes: row.total_labor_minutes ?? 0,
    total_labor_cents: row.total_labor_cents ?? 0,
    displacement_type: row.displacement_type ?? "none",
    displacement_count: row.displacement_count ?? 0,
    displacement_km_total: Number(row.displacement_km_total ?? 0),
    displacement_rate_cents: row.displacement_rate_cents ?? 0,
    displacement_total_cents: row.displacement_total_cents ?? 0,
    displacement_notes: row.displacement_notes ?? null,
    materials_total_cents: row.materials_total_cents ?? 0,
    grand_total_cents: row.grand_total_cents ?? 0,
    notes: row.notes ?? null,
    finalized_at: row.finalized_at ?? null,
    finalized_by: row.finalized_by ?? null,
  };
}

export const getOrderFinancials = createServerFn({ method: "GET" })
  .middleware([requireSupabaseAuth])
  .inputValidator((data: { orderId: string }) => data)
  .handler(async ({ data, context }) => {
    const sb = context.supabase as any;
    const [labor, fin] = await Promise.all([
      sb
        .from("service_order_labor_entries")
        .select(LABOR_SELECT)
        .eq("service_order_id", data.orderId)
        .order("work_date", { ascending: true })
        .order("start_time", { ascending: true }),
      sb
        .from("service_order_financials")
        .select("*")
        .eq("service_order_id", data.orderId)
        .maybeSingle(),
    ]);
    if (labor.error) throw new Error(labor.error.message);
    if (fin.error) throw new Error(fin.error.message);
    return {
      entries: (labor.data ?? []).map(normalizeLabor),
      financials: normalizeFinancials(fin.data),
    };
  });

export const listTechnicianLaborHistory = createServerFn({ method: "GET" })
  .middleware([requireSupabaseAuth])
  .handler(async ({ context }) => {
    const sb = context.supabase as any;
    const { data, error } = await sb
      .from("service_order_labor_entries")
      .select(TECHNICIAN_HISTORY_SELECT)
      .order("work_date", { ascending: false })
      .order("start_time", { ascending: false });

    if (error) throw new Error(error.message);
    return (data ?? []).map(normalizeTechnicianHistory);
  });

function validateInput(input: FinalizeOrderInput) {
  if (!input.order_id) throw new Error("OS inválida.");
  if (!Array.isArray(input.entries) || input.entries.length === 0) {
    throw new Error("Adicione ao menos um apontamento de horas.");
  }
  for (const e of input.entries) {
    if (!e.technician_id) throw new Error("Selecione o técnico para todos os apontamentos.");
    if (!e.work_date) throw new Error("Informe a data do apontamento.");
    if (!e.hourly_rate_cents || e.hourly_rate_cents <= 0) {
      throw new Error("Informe o valor da hora de todos os técnicos antes de finalizar.");
    }
    // Throws if invalid
    computeDurationMinutes(e.start_time, e.end_time);
  }
  const d = input.displacement;
  if (d.type === "per_km") {
    if (d.km_total <= 0 || d.rate_cents <= 0) {
      throw new Error("Para deslocamento por km, informe km total e R$/km.");
    }
  }
  if (d.type === "fixed" && d.fixed_total_cents <= 0) {
    throw new Error("Para deslocamento fixo, informe o valor total.");
  }
}

export const finalizeServiceOrder = createServerFn({ method: "POST" })
  .middleware([requireSupabaseAuth])
  .inputValidator((data: FinalizeOrderInput) => data)
  .handler(async ({ data, context }) => {
    validateInput(data);
    const sb = context.supabase as any;

    // 1) Replace labor entries.
    const computed = data.entries.map((e: LaborEntryInput) => {
      const duration = computeDurationMinutes(e.start_time, e.end_time);
      return {
        service_order_id: data.order_id,
        technician_id: e.technician_id,
        role: e.role ?? null,
        work_date: e.work_date,
        start_time: e.start_time.length === 5 ? `${e.start_time}:00` : e.start_time,
        end_time: e.end_time.length === 5 ? `${e.end_time}:00` : e.end_time,
        duration_minutes: duration,
        hourly_rate_cents: Math.round(e.hourly_rate_cents),
        subtotal_cents: computeSubtotalCents(duration, e.hourly_rate_cents),
        description: e.description ?? null,
        created_by: context.userId,
      };
    });

    const totalLaborMinutes = computed.reduce((a, x) => a + x.duration_minutes, 0);
    const totalLaborCents = computed.reduce((a, x) => a + x.subtotal_cents, 0);
    const displacementCents = computeDisplacementCents(data.displacement as DisplacementInput);
    const materialsCents = Math.max(0, Math.round(data.materials_total_cents || 0));
    const grandTotal = totalLaborCents + displacementCents + materialsCents;

    const { error: delErr } = await sb
      .from("service_order_labor_entries")
      .delete()
      .eq("service_order_id", data.order_id);
    if (delErr) throw new Error(delErr.message);

    const { error: insErr } = await sb.from("service_order_labor_entries").insert(computed);
    if (insErr) throw new Error(insErr.message);

    // 2) Upsert financial summary.
    const now = new Date().toISOString();
    const finRow = {
      service_order_id: data.order_id,
      total_labor_minutes: totalLaborMinutes,
      total_labor_cents: totalLaborCents,
      displacement_type: data.displacement.type,
      displacement_count: Math.max(0, Math.round(data.displacement.count || 0)),
      displacement_km_total: Math.max(0, Number(data.displacement.km_total) || 0),
      displacement_rate_cents: Math.max(0, Math.round(data.displacement.rate_cents || 0)),
      displacement_total_cents: displacementCents,
      displacement_notes: data.displacement.notes ?? null,
      materials_total_cents: materialsCents,
      grand_total_cents: grandTotal,
      notes: data.notes ?? null,
      finalized_at: now,
      finalized_by: context.userId,
    };
    const { error: upErr } = await sb
      .from("service_order_financials")
      .upsert(finRow, { onConflict: "service_order_id" });
    if (upErr) throw new Error(upErr.message);

    // 3) Update OS status + legacy fields.
    const weightedRate =
      totalLaborMinutes > 0 ? Math.round((totalLaborCents * 60) / totalLaborMinutes) / 100 : null;
    const { error: osErr } = await sb
      .from("service_orders")
      .update({
        status: "finished",
        finished_at: now,
        closed_at: now,
        worked_minutes: totalLaborMinutes,
        hour_rate: weightedRate,
      })
      .eq("id", data.order_id);
    if (osErr) throw new Error(osErr.message);

    return { ok: true };
  });

/** Persist hourly rate update on technician master record. */
export const updateTechnicianHourlyRate = createServerFn({ method: "POST" })
  .middleware([requireSupabaseAuth])
  .inputValidator((data: { id: string; hourly_rate_cents: number | null }) => data)
  .handler(async ({ data, context }) => {
    const sb = context.supabase as any;
    const { error } = await sb
      .from("technicians")
      .update({ hourly_rate_cents: data.hourly_rate_cents })
      .eq("id", data.id);
    if (error) throw new Error(error.message);
    return { ok: true };
  });

/** Compute totals helper exposed for re-use. */
export { computeTotals };
