/* eslint-disable @typescript-eslint/no-explicit-any -- Supabase generated types don't yet include new tables (regenerated by Cloud after migration). */
import { createServerFn } from "@tanstack/react-start";
import { requireSupabaseAuth } from "@/integrations/supabase/auth-middleware";

async function assertAdmin(context: { supabase: any; userId: string }) {
  const { data, error } = await (context.supabase as any).rpc("is_admin");
  if (error) throw new Error(error.message);
  if (!data) throw new Error("Acesso restrito ao administrador.");
}
import {
  computeDurationMinutes,
  computeDisplacementCents,
  computeSubtotalCents,
  computeTotals,
} from "@/lib/serviceOrders/finance";
import type {
  DisplacementInput,
  FinalizeOrderInput,
  LaborEntry,
  LaborEntryInput,
  OrderFinancials,
} from "@/types/financials";

const LABOR_SELECT = `
  id, service_order_id, technician_id, role, work_date, start_time, end_time,
  duration_minutes, hourly_rate_cents, subtotal_cents, description,
  technician:technicians(id, full_name, role)
`;

const TIME_SESSION_SELECT = `
  id, service_order_id, technician_id, kind, started_at, ended_at,
  duration_minutes, end_reason
`;

type ClosedWorkSession = {
  id: string;
  technician_id: string;
  started_at: string;
  ended_at: string;
  duration_minutes: number;
};

const SP_DATE = new Intl.DateTimeFormat("en-CA", {
  timeZone: "America/Sao_Paulo",
  year: "numeric",
  month: "2-digit",
  day: "2-digit",
});
const SP_TIME = new Intl.DateTimeFormat("en-GB", {
  timeZone: "America/Sao_Paulo",
  hour: "2-digit",
  minute: "2-digit",
  second: "2-digit",
  hour12: false,
});

function spDate(iso: string): string {
  return SP_DATE.format(new Date(iso));
}
function spTime(iso: string): string {
  return SP_TIME.format(new Date(iso));
}

function minutesBetween(a: string, b: string): number {
  const ta = new Date(a).getTime();
  const tb = new Date(b).getTime();
  if (!Number.isFinite(ta) || !Number.isFinite(tb) || tb <= ta) return 0;
  return Math.max(0, Math.round((tb - ta) / 60000));
}

/**
 * Rebuild LaborEntry list from closed work sessions (source of truth).
 * One entry per closed work interval (started→paused / resumed→finished).
 * Pauses are automatically excluded because each row is a single active window.
 */
function deriveEntriesFromSessions(
  orderId: string,
  sessions: ClosedWorkSession[],
  existingEntries: LaborEntry[],
  technicianFallback: Map<
    string,
    { id: string; full_name: string; role: string | null; hourly_rate_cents: number | null }
  >,
): LaborEntry[] {
  // Rate + technician object per technician_id, prefer existing labor entry.
  const rateByTech = new Map<string, number>();
  const techObjByTech = new Map<string, LaborEntry["technician"]>();
  const roleByTech = new Map<string, string | null>();
  for (const e of existingEntries) {
    if (!e.technician_id) continue;
    if (!rateByTech.has(e.technician_id) && e.hourly_rate_cents > 0) {
      rateByTech.set(e.technician_id, e.hourly_rate_cents);
    }
    if (!techObjByTech.has(e.technician_id) && e.technician) {
      techObjByTech.set(e.technician_id, e.technician);
    }
    if (!roleByTech.has(e.technician_id)) {
      roleByTech.set(e.technician_id, e.role);
    }
  }
  for (const [id, t] of technicianFallback) {
    if (!rateByTech.has(id) && t.hourly_rate_cents != null) {
      rateByTech.set(id, t.hourly_rate_cents);
    }
    if (!techObjByTech.has(id)) {
      techObjByTech.set(id, { id: t.id, full_name: t.full_name, role: t.role });
    }
  }

  // Group + sort per tech.
  const byTech = new Map<string, ClosedWorkSession[]>();
  for (const s of sessions) {
    const list = byTech.get(s.technician_id) ?? [];
    list.push(s);
    byTech.set(s.technician_id, list);
  }

  const out: LaborEntry[] = [];
  for (const [techId, list] of byTech) {
    list.sort((a, b) => a.started_at.localeCompare(b.started_at));
    const rate = rateByTech.get(techId) ?? 0;
    const techObj = techObjByTech.get(techId) ?? null;
    const role = roleByTech.get(techId) ?? null;
    list.forEach((s, idx) => {
      const workDate = spDate(s.started_at);
      const endDate = spDate(s.ended_at);
      const startTime = spTime(s.started_at);
      // Edge case: session crosses midnight — clamp end to 23:59:59.
      const endTime = endDate !== workDate ? "23:59:59" : spTime(s.ended_at);
      const duration =
        s.duration_minutes && s.duration_minutes > 0
          ? s.duration_minutes
          : minutesBetween(s.started_at, s.ended_at);
      const subtotal = computeSubtotalCents(duration, rate);
      out.push({
        id: `derived:${s.id}`,
        service_order_id: orderId,
        technician_id: techId,
        role,
        work_date: workDate,
        start_time: startTime,
        end_time: endTime,
        duration_minutes: duration,
        hourly_rate_cents: rate,
        subtotal_cents: subtotal,
        description:
          list.length > 1 ? `Intervalo ${idx + 1} de ${list.length}` : "Trabalho executado",
        technician: techObj,
      });
    });
  }

  // Sort globally by date/time so PDF and UI render chronologically.
  out.sort((a, b) => {
    const d = a.work_date.localeCompare(b.work_date);
    if (d !== 0) return d;
    return a.start_time.localeCompare(b.start_time);
  });
  return out;
}

function entriesDiverge(existing: LaborEntry[], derived: LaborEntry[]): boolean {
  if (existing.length !== derived.length) return true;
  const totalExisting = existing.reduce((a, e) => a + (e.duration_minutes ?? 0), 0);
  const totalDerived = derived.reduce((a, e) => a + (e.duration_minutes ?? 0), 0);
  if (totalExisting !== totalDerived) return true;
  // Compare start/end/duration ordered.
  const key = (e: LaborEntry) =>
    `${e.technician_id}|${e.work_date}|${e.start_time.slice(0, 5)}|${e.end_time.slice(0, 5)}|${e.duration_minutes}`;
  const setE = new Set(existing.map(key));
  for (const d of derived) if (!setE.has(key(d))) return true;
  return false;
}

const TECHNICIAN_HISTORY_SELECT = `
  id, service_order_id, technician_id, role, work_date, start_time, end_time,
  duration_minutes, hourly_rate_cents, subtotal_cents, description,
  service_order:service_orders!service_order_labor_entries_service_order_id_fkey(
    id, number, title, status, opened_at, started_at, finished_at, closed_at,
    service_type, service_type_other,
    client:clients!service_orders_client_id_fkey(id, name, unit),
    client_unit:client_units!service_orders_client_unit_id_fkey(id, name, sector, city, state)
  )
`;

export type TechnicianLaborHistoryRow = {
  id: string;
  service_order_id: string;
  technician_id: string | null;
  role: string | null;
  work_date: string;
  start_time: string;
  end_time: string;
  duration_minutes: number;
  hourly_rate_cents: number;
  subtotal_cents: number;
  description: string | null;
  service_order: {
    id: string;
    number: number;
    title: string;
    status: string;
    opened_at: string;
    started_at: string | null;
    finished_at: string | null;
    closed_at: string | null;
    service_type: string | null;
    service_type_other: string | null;
    client: { id: string; name: string; unit: string | null } | null;
    client_unit: {
      id: string;
      name: string;
      sector: string | null;
      city: string | null;
      state: string | null;
    } | null;
  } | null;
};

function normalizeLabor(row: any): LaborEntry {
  return {
    id: row.id,
    service_order_id: row.service_order_id,
    technician_id: row.technician_id ?? null,
    role: row.role ?? null,
    work_date: row.work_date,
    start_time: row.start_time,
    end_time: row.end_time,
    duration_minutes: row.duration_minutes ?? 0,
    hourly_rate_cents: row.hourly_rate_cents ?? 0,
    subtotal_cents: row.subtotal_cents ?? 0,
    description: row.description ?? null,
    technician: row.technician
      ? {
          id: row.technician.id,
          full_name: row.technician.full_name,
          role: row.technician.role ?? null,
        }
      : null,
  };
}

function normalizeTechnicianHistory(row: any): TechnicianLaborHistoryRow {
  return {
    id: row.id,
    service_order_id: row.service_order_id,
    technician_id: row.technician_id ?? null,
    role: row.role ?? null,
    work_date: row.work_date,
    start_time: row.start_time,
    end_time: row.end_time,
    duration_minutes: row.duration_minutes ?? 0,
    hourly_rate_cents: row.hourly_rate_cents ?? 0,
    subtotal_cents: row.subtotal_cents ?? 0,
    description: row.description ?? null,
    service_order: row.service_order
      ? {
          id: row.service_order.id,
          number: row.service_order.number,
          title: row.service_order.title,
          status: row.service_order.status,
          opened_at: row.service_order.opened_at,
          started_at: row.service_order.started_at ?? null,
          finished_at: row.service_order.finished_at ?? null,
          closed_at: row.service_order.closed_at ?? null,
          service_type: row.service_order.service_type ?? null,
          service_type_other: row.service_order.service_type_other ?? null,
          client: row.service_order.client ?? null,
          client_unit: row.service_order.client_unit ?? null,
        }
      : null,
  };
}

function normalizeFinancials(row: any): OrderFinancials | null {
  if (!row) return null;
  return {
    service_order_id: row.service_order_id,
    total_labor_minutes: row.total_labor_minutes ?? 0,
    total_labor_cents: row.total_labor_cents ?? 0,
    displacement_type: row.displacement_type ?? "none",
    displacement_count: row.displacement_count ?? 0,
    displacement_km_total: Number(row.displacement_km_total ?? 0),
    displacement_rate_cents: row.displacement_rate_cents ?? 0,
    displacement_total_cents: row.displacement_total_cents ?? 0,
    displacement_notes: row.displacement_notes ?? null,
    materials_total_cents: row.materials_total_cents ?? 0,
    grand_total_cents: row.grand_total_cents ?? 0,
    notes: row.notes ?? null,
    finalized_at: row.finalized_at ?? null,
    finalized_by: row.finalized_by ?? null,
    labor_entries_adjusted_at: row.labor_entries_adjusted_at ?? null,
    labor_entries_adjusted_by: row.labor_entries_adjusted_by ?? null,
  };
}

async function upsertFinancialLaborTotals(
  sb: any,
  orderId: string,
  totals: { totalLaborMinutes: number; totalLaborCents: number },
  adjustedBy?: string | null,
): Promise<OrderFinancials | null> {
  const { data: fin } = await sb
    .from("service_order_financials")
    .select("*")
    .eq("service_order_id", orderId)
    .maybeSingle();

  const displacementCents = fin?.displacement_total_cents ?? 0;
  const materialsCents = fin?.materials_total_cents ?? 0;
  const patch: Record<string, unknown> = {
    service_order_id: orderId,
    total_labor_minutes: totals.totalLaborMinutes,
    total_labor_cents: totals.totalLaborCents,
    grand_total_cents: totals.totalLaborCents + displacementCents + materialsCents,
  };
  if (adjustedBy) {
    patch.labor_entries_adjusted_at = new Date().toISOString();
    patch.labor_entries_adjusted_by = adjustedBy;
  }

  const { data: updated, error } = await sb
    .from("service_order_financials")
    .upsert(patch, { onConflict: "service_order_id" })
    .select("*")
    .maybeSingle();
  if (error) throw new Error(error.message);

  const weightedRate =
    totals.totalLaborMinutes > 0
      ? Math.round((totals.totalLaborCents * 60) / totals.totalLaborMinutes) / 100
      : null;
  await sb
    .from("service_orders")
    .update({ worked_minutes: totals.totalLaborMinutes, hour_rate: weightedRate })
    .eq("id", orderId);

  return normalizeFinancials(updated);
}

export const getOrderFinancials = createServerFn({ method: "GET" })
  .middleware([requireSupabaseAuth])
  .inputValidator((data: { orderId: string }) => data)
  .handler(async ({ data, context }) => {
    await assertAdmin(context);
    const sb = context.supabase as any;
    const [labor, fin, sessionsRes] = await Promise.all([
      sb
        .from("service_order_labor_entries")
        .select(LABOR_SELECT)
        .eq("service_order_id", data.orderId)
        .order("work_date", { ascending: true })
        .order("start_time", { ascending: true }),
      sb
        .from("service_order_financials")
        .select("*")
        .eq("service_order_id", data.orderId)
        .maybeSingle(),
      sb
        .from("service_order_time_sessions")
        .select(TIME_SESSION_SELECT)
        .eq("service_order_id", data.orderId)
        .eq("kind", "work")
        .not("ended_at", "is", null)
        .order("started_at", { ascending: true }),
    ]);
    if (labor.error) throw new Error(labor.error.message);
    if (fin.error) throw new Error(fin.error.message);

    const storedEntries: LaborEntry[] = (labor.data ?? []).map(normalizeLabor);
    const financials = normalizeFinancials(fin.data);
    const rawSessions = sessionsRes?.error ? [] : (sessionsRes?.data ?? []);
    const closedWorkSessions: ClosedWorkSession[] = rawSessions
      .filter(
        (s: any) =>
          s.kind === "work" &&
          s.technician_id &&
          s.started_at &&
          s.ended_at &&
          (s.duration_minutes ?? 0) > 0,
      )
      .map((s: any) => ({
        id: s.id,
        technician_id: s.technician_id,
        started_at: s.started_at,
        ended_at: s.ended_at,
        duration_minutes: s.duration_minutes ?? 0,
      }));

    if (closedWorkSessions.length === 0) {
      // No time-tracking data — trust manually entered labor entries.
      if (storedEntries.length > 0) {
        const totalLaborMinutes = storedEntries.reduce((a, e) => a + e.duration_minutes, 0);
        const totalLaborCents = storedEntries.reduce((a, e) => a + e.subtotal_cents, 0);
        const effectiveFinancials =
          !financials ||
          financials.total_labor_minutes !== totalLaborMinutes ||
          financials.total_labor_cents !== totalLaborCents
            ? await upsertFinancialLaborTotals(sb, data.orderId, {
                totalLaborMinutes,
                totalLaborCents,
              })
            : financials;
        return { entries: storedEntries, financials: effectiveFinancials };
      }
      return { entries: storedEntries, financials };
    }

    // Fetch technician fallback for sessions whose tech has no existing entry.
    const missingTechIds = Array.from(
      new Set(
        closedWorkSessions
          .map((s) => s.technician_id)
          .filter((id) => !storedEntries.some((e) => e.technician_id === id)),
      ),
    );
    const techFallback = new Map<
      string,
      { id: string; full_name: string; role: string | null; hourly_rate_cents: number | null }
    >();
    if (missingTechIds.length > 0) {
      const { data: techRows, error: techErr } = await sb
        .from("technicians")
        .select("id, full_name, role, hourly_rate_cents")
        .in("id", missingTechIds);
      if (!techErr && techRows) {
        for (const t of techRows) {
          techFallback.set(t.id, {
            id: t.id,
            full_name: t.full_name,
            role: t.role ?? null,
            hourly_rate_cents: t.hourly_rate_cents ?? null,
          });
        }
      }
    }

    const derivedEntries = deriveEntriesFromSessions(
      data.orderId,
      closedWorkSessions,
      storedEntries,
      techFallback,
    );

    // Once an admin has manually edited/deleted/added labor rows, the persisted
    // labor table becomes the canonical source. Do not recreate deleted rows
    // from the immutable time-session audit trail.
    if (financials?.labor_entries_adjusted_at) {
      return { entries: storedEntries, financials };
    }

    // If materialized labor rows already exist, they are the editable working
    // copy for admin review/PDF/reporting. Do not replace them on every read,
    // otherwise deleting a row would be undone by the session audit trail.
    if (storedEntries.length > 0) {
      const totalLaborMinutes = storedEntries.reduce((a, e) => a + e.duration_minutes, 0);
      const totalLaborCents = storedEntries.reduce((a, e) => a + e.subtotal_cents, 0);
      const effectiveFinancials =
        !financials ||
        financials.total_labor_minutes !== totalLaborMinutes ||
        financials.total_labor_cents !== totalLaborCents
          ? await upsertFinancialLaborTotals(sb, data.orderId, {
              totalLaborMinutes,
              totalLaborCents,
            })
          : financials;
      return { entries: storedEntries, financials: effectiveFinancials };
    }

    // First editable read: materialize derived sessions as the admin working
    // copy, even if some rates are zero, so the fields can be corrected inline.
    let effectiveFinancials = financials;
    if (entriesDiverge(storedEntries, derivedEntries)) {
      try {
        const totalLaborMinutes = derivedEntries.reduce((a, e) => a + e.duration_minutes, 0);
        const totalLaborCents = derivedEntries.reduce((a, e) => a + e.subtotal_cents, 0);

        const inserts = derivedEntries.map((e) => ({
          service_order_id: data.orderId,
          technician_id: e.technician_id,
          role: e.role,
          work_date: e.work_date,
          start_time: e.start_time.length === 5 ? `${e.start_time}:00` : e.start_time,
          end_time: e.end_time.length === 5 ? `${e.end_time}:00` : e.end_time,
          duration_minutes: e.duration_minutes,
          hourly_rate_cents: e.hourly_rate_cents,
          subtotal_cents: e.subtotal_cents,
          description: e.description,
          created_by: context.userId,
        }));

        const { error: delErr } = await sb
          .from("service_order_labor_entries")
          .delete()
          .eq("service_order_id", data.orderId);
        if (!delErr) {
          const { error: insErr } = await sb
            .from("service_order_labor_entries")
            .insert(inserts);
          if (!insErr) {
            effectiveFinancials = await upsertFinancialLaborTotals(sb, data.orderId, {
              totalLaborMinutes,
              totalLaborCents,
            });

            // Re-fetch canonical entries so IDs are real (not "derived:*").
            const { data: refreshed } = await sb
              .from("service_order_labor_entries")
              .select(LABOR_SELECT)
              .eq("service_order_id", data.orderId)
              .order("work_date", { ascending: true })
              .order("start_time", { ascending: true });
            if (refreshed) {
              return {
                entries: refreshed.map(normalizeLabor),
                financials: effectiveFinancials,
              };
            }
          }
        }
      } catch {
        // Self-heal is best-effort; fall through to derived response.
      }
    } else if (financials) {
      // No self-heal but derived may still differ; ensure returned totals match derived.
      const totalLaborMinutes = derivedEntries.reduce((a, e) => a + e.duration_minutes, 0);
      const totalLaborCents = derivedEntries.reduce((a, e) => a + e.subtotal_cents, 0);
      const displacementCents = financials.displacement_total_cents ?? 0;
      const materialsCents = financials.materials_total_cents ?? 0;
      effectiveFinancials = {
        ...financials,
        total_labor_minutes: totalLaborMinutes,
        total_labor_cents: totalLaborCents,
        grand_total_cents: totalLaborCents + displacementCents + materialsCents,
      };
    }

    return { entries: derivedEntries, financials: effectiveFinancials };
  });

export const listServiceOrderFinancialSummaries = createServerFn({ method: "GET" })
  .middleware([requireSupabaseAuth])
  .handler(async ({ context }) => {
    await assertAdmin(context);
    const sb = context.supabase as any;
    const { data, error } = await sb.from("service_order_financials").select("*");
    if (error) throw new Error(error.message);
    return (data ?? []).map(normalizeFinancials).filter(Boolean) as OrderFinancials[];
  });

export const listTechnicianLaborHistory = createServerFn({ method: "GET" })
  .middleware([requireSupabaseAuth])
  .handler(async ({ context }) => {
    await assertAdmin(context);
    const sb = context.supabase as any;
    const { data, error } = await sb
      .from("service_order_labor_entries")
      .select(TECHNICIAN_HISTORY_SELECT)
      .order("work_date", { ascending: false })
      .order("start_time", { ascending: false });

    if (error) throw new Error(error.message);
    return (data ?? []).map(normalizeTechnicianHistory);
  });

function validateInput(input: FinalizeOrderInput) {
  if (!input.order_id) throw new Error("OS inválida.");
  if (!Array.isArray(input.entries) || input.entries.length === 0) {
    throw new Error("Adicione ao menos um apontamento de horas.");
  }
  for (const e of input.entries) {
    if (!e.technician_id) throw new Error("Selecione o técnico para todos os apontamentos.");
    if (!e.work_date) throw new Error("Informe a data do apontamento.");
    if (!e.hourly_rate_cents || e.hourly_rate_cents <= 0) {
      throw new Error("Informe o valor da hora de todos os técnicos antes de finalizar.");
    }
    // Throws if invalid
    computeDurationMinutes(e.start_time, e.end_time);
  }
  const d = input.displacement;
  if (d.type === "per_km") {
    if (d.km_total <= 0 || d.rate_cents <= 0) {
      throw new Error("Para deslocamento por km, informe km total e R$/km.");
    }
  }
  if (d.type === "fixed" && d.fixed_total_cents <= 0) {
    throw new Error("Para deslocamento fixo, informe o valor total.");
  }
}

export const finalizeServiceOrder = createServerFn({ method: "POST" })
  .middleware([requireSupabaseAuth])
  .inputValidator((data: FinalizeOrderInput) => data)
  .handler(async ({ data, context }) => {
    await assertAdmin(context);
    validateInput(data);
    const sb = context.supabase as any;

    // 1) Replace labor entries.
    const computed = data.entries.map((e: LaborEntryInput) => {
      const duration = computeDurationMinutes(e.start_time, e.end_time);
      return {
        service_order_id: data.order_id,
        technician_id: e.technician_id,
        role: e.role ?? null,
        work_date: e.work_date,
        start_time: e.start_time.length === 5 ? `${e.start_time}:00` : e.start_time,
        end_time: e.end_time.length === 5 ? `${e.end_time}:00` : e.end_time,
        duration_minutes: duration,
        hourly_rate_cents: Math.round(e.hourly_rate_cents),
        subtotal_cents: computeSubtotalCents(duration, e.hourly_rate_cents),
        description: e.description ?? null,
        created_by: context.userId,
      };
    });

    const totalLaborMinutes = computed.reduce((a, x) => a + x.duration_minutes, 0);
    const totalLaborCents = computed.reduce((a, x) => a + x.subtotal_cents, 0);
    const displacementCents = computeDisplacementCents(data.displacement as DisplacementInput);
    const materialsCents = Math.max(0, Math.round(data.materials_total_cents || 0));
    const grandTotal = totalLaborCents + displacementCents + materialsCents;

    const { error: delErr } = await sb
      .from("service_order_labor_entries")
      .delete()
      .eq("service_order_id", data.order_id);
    if (delErr) throw new Error(delErr.message);

    const { error: insErr } = await sb.from("service_order_labor_entries").insert(computed);
    if (insErr) throw new Error(insErr.message);

    // 2) Upsert financial summary.
    const now = new Date().toISOString();
    const finRow = {
      service_order_id: data.order_id,
      total_labor_minutes: totalLaborMinutes,
      total_labor_cents: totalLaborCents,
      displacement_type: data.displacement.type,
      displacement_count: Math.max(0, Math.round(data.displacement.count || 0)),
      displacement_km_total: Math.max(0, Number(data.displacement.km_total) || 0),
      displacement_rate_cents: Math.max(0, Math.round(data.displacement.rate_cents || 0)),
      displacement_total_cents: displacementCents,
      displacement_notes: data.displacement.notes ?? null,
      materials_total_cents: materialsCents,
      grand_total_cents: grandTotal,
      notes: data.notes ?? null,
      finalized_at: now,
      finalized_by: context.userId,
      labor_entries_adjusted_at: now,
      labor_entries_adjusted_by: context.userId,
    };
    const { error: upErr } = await sb
      .from("service_order_financials")
      .upsert(finRow, { onConflict: "service_order_id" });
    if (upErr) throw new Error(upErr.message);

    // 3) Update OS status + legacy fields.
    const weightedRate =
      totalLaborMinutes > 0 ? Math.round((totalLaborCents * 60) / totalLaborMinutes) / 100 : null;
    const { error: osErr } = await sb
      .from("service_orders")
      .update({
        status: "finished",
        finished_at: now,
        closed_at: now,
        worked_minutes: totalLaborMinutes,
        hour_rate: weightedRate,
      })
      .eq("id", data.order_id);
    if (osErr) throw new Error(osErr.message);

    return { ok: true };
  });

/** Persist hourly rate update on technician master record. */
export const updateTechnicianHourlyRate = createServerFn({ method: "POST" })
  .middleware([requireSupabaseAuth])
  .inputValidator((data: { id: string; hourly_rate_cents: number | null }) => data)
  .handler(async ({ data, context }) => {
    const sb = context.supabase as any;
    const { error } = await sb
      .from("technicians")
      .update({ hourly_rate_cents: data.hourly_rate_cents })
      .eq("id", data.id);
    if (error) throw new Error(error.message);
    return { ok: true };
  });

/** Compute totals helper exposed for re-use. */
export { computeTotals };

/* -------------------------------------------------------------------------- */
/* Inline editing of labor entries (post-finalization)                        */
/* -------------------------------------------------------------------------- */

function normalizeTime(v: string): string {
  const m = /^(\d{1,2}):(\d{2})(?::(\d{2}))?$/.exec((v || "").trim());
  if (!m) throw new Error(`Hora inválida: ${v}`);
  const h = Number(m[1]);
  const mi = Number(m[2]);
  if (h < 0 || h > 23 || mi < 0 || mi > 59) throw new Error(`Hora inválida: ${v}`);
  return `${String(h).padStart(2, "0")}:${String(mi).padStart(2, "0")}:${m[3] ?? "00"}`;
}

/** Recompute financial summary + OS legacy fields from current labor entries. */
async function recomputeOrderTotals(sb: any, orderId: string, adjustedBy?: string | null) {
  const { data: rows, error } = await sb
    .from("service_order_labor_entries")
    .select("duration_minutes, subtotal_cents")
    .eq("service_order_id", orderId);
  if (error) throw new Error(error.message);
  const totalLaborMinutes = (rows ?? []).reduce(
    (a: number, r: any) => a + (r.duration_minutes ?? 0),
    0,
  );
  const totalLaborCents = (rows ?? []).reduce(
    (a: number, r: any) => a + (r.subtotal_cents ?? 0),
    0,
  );

  await upsertFinancialLaborTotals(
    sb,
    orderId,
    { totalLaborMinutes, totalLaborCents },
    adjustedBy,
  );
}

/**
 * If any labor entry for this order is still "derived:*" (i.e. never
 * materialized), force a self-heal read to persist them before editing.
 */
async function ensureEntriesPersisted(sb: any, orderId: string, context: any) {
  const { data } = await sb
    .from("service_order_labor_entries")
    .select("id")
    .eq("service_order_id", orderId)
    .limit(1);
  if (!data || data.length === 0) {
    // Nothing persisted — trigger self-heal via getOrderFinancials's inner logic.
    // Simplest reliable approach: return; the caller pre-fetches getOrderFinancials.
  }
  void context;
}

type LaborEntryPatch = Partial<{
  technician_id: string;
  role: string | null;
  work_date: string;
  start_time: string;
  end_time: string;
  hourly_rate_cents: number;
  description: string | null;
}>;

export const updateLaborEntry = createServerFn({ method: "POST" })
  .middleware([requireSupabaseAuth])
  .inputValidator((data: { entryId: string; patch: LaborEntryPatch }) => data)
  .handler(async ({ data, context }) => {
    await assertAdmin(context);
    if (!data.entryId || data.entryId.startsWith("derived:")) {
      throw new Error(
        "Este apontamento ainda não foi persistido. Abra o resumo financeiro para consolidar antes de editar.",
      );
    }
    const sb = context.supabase as any;

    const { data: current, error: curErr } = await sb
      .from("service_order_labor_entries")
      .select("*")
      .eq("id", data.entryId)
      .maybeSingle();
    if (curErr) throw new Error(curErr.message);
    if (!current) throw new Error("Apontamento não encontrado.");

    const next = {
      technician_id: data.patch.technician_id ?? current.technician_id,
      role: data.patch.role !== undefined ? data.patch.role : current.role,
      work_date: data.patch.work_date ?? current.work_date,
      start_time: normalizeTime(data.patch.start_time ?? current.start_time),
      end_time: normalizeTime(data.patch.end_time ?? current.end_time),
      hourly_rate_cents:
        data.patch.hourly_rate_cents != null
          ? Math.round(data.patch.hourly_rate_cents)
          : current.hourly_rate_cents,
      description:
        data.patch.description !== undefined ? data.patch.description : current.description,
    };

    if (!next.technician_id) throw new Error("Selecione um técnico válido.");
    if (!(next.hourly_rate_cents > 0)) throw new Error("Informe um valor de R$/h válido.");

    const duration = computeDurationMinutes(
      next.start_time.slice(0, 5),
      next.end_time.slice(0, 5),
    );
    const subtotal = computeSubtotalCents(duration, next.hourly_rate_cents);

    const { data: updatedRows, error: upErr } = await sb
      .from("service_order_labor_entries")
      .update({
        technician_id: next.technician_id,
        role: next.role,
        work_date: next.work_date,
        start_time: next.start_time,
        end_time: next.end_time,
        duration_minutes: duration,
        hourly_rate_cents: next.hourly_rate_cents,
        subtotal_cents: subtotal,
        description: next.description,
      })
      .eq("id", data.entryId)
      .select("id");
    if (upErr) throw new Error(upErr.message);
    if (!updatedRows || updatedRows.length !== 1) {
      throw new Error("Não foi possível confirmar a atualização do apontamento.");
    }

    await recomputeOrderTotals(sb, current.service_order_id, context.userId);
    return { ok: true };
  });

export const deleteLaborEntry = createServerFn({ method: "POST" })
  .middleware([requireSupabaseAuth])
  .inputValidator((data: { entryId: string }) => data)
  .handler(async ({ data, context }) => {
    await assertAdmin(context);
    if (!data.entryId || data.entryId.startsWith("derived:")) {
      throw new Error("Apontamento ainda não consolidado.");
    }
    const sb = context.supabase as any;
    const { data: current, error: curErr } = await sb
      .from("service_order_labor_entries")
      .select("service_order_id")
      .eq("id", data.entryId)
      .maybeSingle();
    if (curErr) throw new Error(curErr.message);
    if (!current) throw new Error("Apontamento não encontrado.");

    const { data: deletedRows, error: delErr } = await sb
      .from("service_order_labor_entries")
      .delete()
      .eq("id", data.entryId)
      .select("id");
    if (delErr) throw new Error(delErr.message);
    if (!deletedRows || deletedRows.length !== 1) {
      throw new Error("Não foi possível confirmar a exclusão do apontamento.");
    }

    await recomputeOrderTotals(sb, current.service_order_id, context.userId);
    return { ok: true };
  });

export const createLaborEntry = createServerFn({ method: "POST" })
  .middleware([requireSupabaseAuth])
  .inputValidator(
    (data: {
      orderId: string;
      entry: {
        technician_id: string;
        role?: string | null;
        work_date: string;
        start_time: string;
        end_time: string;
        hourly_rate_cents: number;
        description?: string | null;
      };
    }) => data,
  )
  .handler(async ({ data, context }) => {
    await assertAdmin(context);
    const sb = context.supabase as any;
    const e = data.entry;
    if (!e.technician_id) throw new Error("Selecione um técnico.");
    if (!(e.hourly_rate_cents > 0)) throw new Error("Informe um valor de R$/h válido.");
    const startNorm = normalizeTime(e.start_time);
    const endNorm = normalizeTime(e.end_time);
    const duration = computeDurationMinutes(startNorm.slice(0, 5), endNorm.slice(0, 5));
    const subtotal = computeSubtotalCents(duration, e.hourly_rate_cents);

    const { error } = await sb.from("service_order_labor_entries").insert({
      service_order_id: data.orderId,
      technician_id: e.technician_id,
      role: e.role ?? null,
      work_date: e.work_date,
      start_time: startNorm,
      end_time: endNorm,
      duration_minutes: duration,
      hourly_rate_cents: Math.round(e.hourly_rate_cents),
      subtotal_cents: subtotal,
      description: e.description ?? "Ajuste manual",
      created_by: context.userId,
    });
    if (error) throw new Error(error.message);

    await recomputeOrderTotals(sb, data.orderId, context.userId);
    return { ok: true };
  });

// Silence unused warning for the placeholder helper.
void ensureEntriesPersisted;
