import { createFileRoute, Link } from "@tanstack/react-router";
import { AppShell } from "@/components/app/AppShell";
import { OrderCard } from "@/components/app/OrderCard";
import { useRole } from "@/components/app/RoleContext";
import { MetricTile, OperationalFlow, PageHero, PrimaryCTA } from "@/components/app/operations";
import { ordens, ordensStats } from "@/lib/mock/serviceOrders";
import { Activity, AlertTriangle, Building2, ClipboardList, Clock, MapPin, Play, Receipt, Route as RouteIcon, ShieldCheck } from "lucide-react";
export const Route = createFileRoute("/_app/dashboard")({ head: () => ({ meta: [{ title: "Central de Operação — Gestão Lemarc" }] }), component: Dashboard });
function Dashboard(){ const {role,name}=useRole(); return <AppShell>{role==="gestor"?<GestorView name={name}/>:<ColaboradorView name={name}/>}</AppShell> }
function GestorView({name}:{name:string}){ const emAndamento=ordens.filter(o=>["running","transit"].includes(o.status)); return <><PageHero eyebrow="Operação de hoje" title={`Olá, ${name.split(" ")[0]}.`} description={`${ordensStats.abertas} OS abertas · ${ordensStats.emExecucao} em execução · ${ordensStats.aguardandoRevisao} aguardando revisão`} action={<PrimaryCTA to="/ordens/nova" icon={ClipboardList}>Nova OS</PrimaryCTA>} />
<div className="mt-4 grid grid-cols-2 gap-3"><MetricTile label="OS abertas" value={ordensStats.abertas} icon={ClipboardList} accent/><MetricTile label="Em execução" value={ordensStats.emExecucao} icon={Activity}/><MetricTile label="Aguard. revisão" value={ordensStats.aguardandoRevisao} hint="prioridade de cobrança" icon={AlertTriangle} accent/><MetricTile label="Valor pré-cobrança" value={`R$ ${Math.round(ordensStats.valorEstimado/1000)}k`} hint="estimativa empresarial" icon={Receipt}/></div>
<div className="mt-4"><OperationalFlow active={1}/></div><section className="mt-5"><Header title="OS em andamento agora" to="/ordens"/><div className="space-y-3">{emAndamento.map(o=><OrderCard key={o.id} ordem={o}/>)}</div></section><section className="mt-5"><Header title="Ordens recentes" to="/ordens"/><div className="space-y-3">{ordens.slice(0,3).map(o=><OrderCard key={o.id} ordem={o}/>)}</div></section></> }
function ColaboradorView({name}:{name:string}){ const minhas=ordens.filter(o=>o.colaborador==="Carlos Henrique Silva"); const p=minhas[0]??ordens[0]; const checks=["Saída","Chegada","Execução","Fotos","Finalização"]; return <><PageHero eyebrow="Tela de campo" title={`Bom dia, ${name.split(" ")[0]}.`} description={`${minhas.length} OS para hoje · status: pronto para atendimento`} icon={ShieldCheck}/><article className="lemarc-liquid-card lemarc-3d-card lemarc-grain mt-4 rounded-3xl p-5"><p className="text-[10px] font-black uppercase tracking-[0.22em] text-primary">Próxima OS</p><h2 className="mt-1 font-display text-xl font-black leading-tight text-foreground">{p.titulo}</h2><div className="mt-3 grid gap-2 text-xs text-muted-foreground"><span className="flex items-center gap-2"><Building2 size={13} className="text-primary"/>{p.cliente} · {p.unidade}</span><span className="flex items-center gap-2"><MapPin size={13} className="text-primary"/>{p.distanciaKm} km · {p.horario} · prioridade {p.prioridade}</span></div><div className="mt-4"><PrimaryCTA to={`/ordens/${p.id}`} icon={Play}>Iniciar atendimento</PrimaryCTA></div></article><div className="mt-4 grid grid-cols-5 gap-2">{checks.map((c,i)=><div key={c} className="rounded-2xl border border-border bg-secondary/40 p-2 text-center"><div className={`mx-auto h-2 w-2 rounded-full ${i<2?"bg-primary":"bg-muted-foreground/40"}`}/><div className="mt-1 truncate text-[9px] font-black uppercase text-muted-foreground">{c}</div></div>)}</div><section className="mt-5"><Header title="OS do dia" to="/ordens"/><div className="space-y-3">{minhas.map(o=><OrderCard key={o.id} ordem={o}/>)}</div></section></> }
function Header({title,to}:{title:string;to:string}){return <div className="mb-2 flex items-center justify-between px-1"><h2 className="section-title flex items-center gap-2"><RouteIcon size={14}/>{title}</h2><Link to={to} className="text-xs font-bold text-primary">Ver todas</Link></div>}
