/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AppRouteImport } from './routes/_app'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AppRelatoriosRouteImport } from './routes/_app.relatorios'
import { Route as AppMaisRouteImport } from './routes/_app.mais'
import { Route as AppDashboardRouteImport } from './routes/_app.dashboard'
import { Route as AppColaboradoresRouteImport } from './routes/_app.colaboradores'
import { Route as AppClientesRouteImport } from './routes/_app.clientes'
import { Route as AppOrdensIndexRouteImport } from './routes/_app.ordens.index'
import { Route as AppColaboradoresIndexRouteImport } from './routes/_app.colaboradores.index'
import { Route as AppClientesIndexRouteImport } from './routes/_app.clientes.index'
import { Route as AppRelatoriosImprimirRouteImport } from './routes/_app.relatorios_.imprimir'
import { Route as AppOrdensNovaRouteImport } from './routes/_app.ordens.nova'
import { Route as AppOrdensIdRouteImport } from './routes/_app.ordens.$id'
import { Route as AppColaboradoresNovoRouteImport } from './routes/_app.colaboradores.novo'
import { Route as AppColaboradoresIdRouteImport } from './routes/_app.colaboradores.$id'
import { Route as AppClientesNovoRouteImport } from './routes/_app.clientes.novo'
import { Route as AppClientesIdIndexRouteImport } from './routes/_app.clientes.$id.index'
import { Route as LovableEmailQueueProcessRouteImport } from './routes/lovable/email/queue/process'
import { Route as AppRelatoriosClienteClientIdRouteImport } from './routes/_app.relatorios_.cliente.$clientId'
import { Route as AppOrdensIdImprimirRouteImport } from './routes/_app.ordens.$id.imprimir'
import { Route as AppColaboradoresIdPrecificacaoRouteImport } from './routes/_app.colaboradores.$id.precificacao'
import { Route as AppColaboradoresIdOrdensRouteImport } from './routes/_app.colaboradores.$id.ordens'
import { Route as AppColaboradoresIdHorasRouteImport } from './routes/_app.colaboradores.$id.horas'
import { Route as AppColaboradoresIdEditarRouteImport } from './routes/_app.colaboradores.$id.editar'
import { Route as AppClientesIdEditarRouteImport } from './routes/_app.clientes.$id.editar'

const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRelatoriosRoute = AppRelatoriosRouteImport.update({
  id: '/relatorios',
  path: '/relatorios',
  getParentRoute: () => AppRoute,
} as any)
const AppMaisRoute = AppMaisRouteImport.update({
  id: '/mais',
  path: '/mais',
  getParentRoute: () => AppRoute,
} as any)
const AppDashboardRoute = AppDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AppRoute,
} as any)
const AppColaboradoresRoute = AppColaboradoresRouteImport.update({
  id: '/colaboradores',
  path: '/colaboradores',
  getParentRoute: () => AppRoute,
} as any)
const AppClientesRoute = AppClientesRouteImport.update({
  id: '/clientes',
  path: '/clientes',
  getParentRoute: () => AppRoute,
} as any)
const AppOrdensIndexRoute = AppOrdensIndexRouteImport.update({
  id: '/ordens/',
  path: '/ordens/',
  getParentRoute: () => AppRoute,
} as any)
const AppColaboradoresIndexRoute = AppColaboradoresIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppColaboradoresRoute,
} as any)
const AppClientesIndexRoute = AppClientesIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppClientesRoute,
} as any)
const AppRelatoriosImprimirRoute = AppRelatoriosImprimirRouteImport.update({
  id: '/relatorios_/imprimir',
  path: '/relatorios/imprimir',
  getParentRoute: () => AppRoute,
} as any)
const AppOrdensNovaRoute = AppOrdensNovaRouteImport.update({
  id: '/ordens/nova',
  path: '/ordens/nova',
  getParentRoute: () => AppRoute,
} as any)
const AppOrdensIdRoute = AppOrdensIdRouteImport.update({
  id: '/ordens/$id',
  path: '/ordens/$id',
  getParentRoute: () => AppRoute,
} as any)
const AppColaboradoresNovoRoute = AppColaboradoresNovoRouteImport.update({
  id: '/novo',
  path: '/novo',
  getParentRoute: () => AppColaboradoresRoute,
} as any)
const AppColaboradoresIdRoute = AppColaboradoresIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => AppColaboradoresRoute,
} as any)
const AppClientesNovoRoute = AppClientesNovoRouteImport.update({
  id: '/novo',
  path: '/novo',
  getParentRoute: () => AppClientesRoute,
} as any)
const AppClientesIdIndexRoute = AppClientesIdIndexRouteImport.update({
  id: '/$id/',
  path: '/$id/',
  getParentRoute: () => AppClientesRoute,
} as any)
const LovableEmailQueueProcessRoute =
  LovableEmailQueueProcessRouteImport.update({
    id: '/lovable/email/queue/process',
    path: '/lovable/email/queue/process',
    getParentRoute: () => rootRouteImport,
  } as any)
const AppRelatoriosClienteClientIdRoute =
  AppRelatoriosClienteClientIdRouteImport.update({
    id: '/relatorios_/cliente/$clientId',
    path: '/relatorios/cliente/$clientId',
    getParentRoute: () => AppRoute,
  } as any)
const AppOrdensIdImprimirRoute = AppOrdensIdImprimirRouteImport.update({
  id: '/imprimir',
  path: '/imprimir',
  getParentRoute: () => AppOrdensIdRoute,
} as any)
const AppColaboradoresIdPrecificacaoRoute =
  AppColaboradoresIdPrecificacaoRouteImport.update({
    id: '/precificacao',
    path: '/precificacao',
    getParentRoute: () => AppColaboradoresIdRoute,
  } as any)
const AppColaboradoresIdOrdensRoute =
  AppColaboradoresIdOrdensRouteImport.update({
    id: '/ordens',
    path: '/ordens',
    getParentRoute: () => AppColaboradoresIdRoute,
  } as any)
const AppColaboradoresIdHorasRoute = AppColaboradoresIdHorasRouteImport.update({
  id: '/horas',
  path: '/horas',
  getParentRoute: () => AppColaboradoresIdRoute,
} as any)
const AppColaboradoresIdEditarRoute =
  AppColaboradoresIdEditarRouteImport.update({
    id: '/editar',
    path: '/editar',
    getParentRoute: () => AppColaboradoresIdRoute,
  } as any)
const AppClientesIdEditarRoute = AppClientesIdEditarRouteImport.update({
  id: '/$id/editar',
  path: '/$id/editar',
  getParentRoute: () => AppClientesRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/clientes': typeof AppClientesRouteWithChildren
  '/colaboradores': typeof AppColaboradoresRouteWithChildren
  '/dashboard': typeof AppDashboardRoute
  '/mais': typeof AppMaisRoute
  '/relatorios': typeof AppRelatoriosRoute
  '/clientes/novo': typeof AppClientesNovoRoute
  '/colaboradores/$id': typeof AppColaboradoresIdRouteWithChildren
  '/colaboradores/novo': typeof AppColaboradoresNovoRoute
  '/ordens/$id': typeof AppOrdensIdRouteWithChildren
  '/ordens/nova': typeof AppOrdensNovaRoute
  '/relatorios/imprimir': typeof AppRelatoriosImprimirRoute
  '/clientes/': typeof AppClientesIndexRoute
  '/colaboradores/': typeof AppColaboradoresIndexRoute
  '/ordens/': typeof AppOrdensIndexRoute
  '/clientes/$id/editar': typeof AppClientesIdEditarRoute
  '/colaboradores/$id/editar': typeof AppColaboradoresIdEditarRoute
  '/colaboradores/$id/horas': typeof AppColaboradoresIdHorasRoute
  '/colaboradores/$id/ordens': typeof AppColaboradoresIdOrdensRoute
  '/colaboradores/$id/precificacao': typeof AppColaboradoresIdPrecificacaoRoute
  '/ordens/$id/imprimir': typeof AppOrdensIdImprimirRoute
  '/relatorios/cliente/$clientId': typeof AppRelatoriosClienteClientIdRoute
  '/lovable/email/queue/process': typeof LovableEmailQueueProcessRoute
  '/clientes/$id/': typeof AppClientesIdIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/dashboard': typeof AppDashboardRoute
  '/mais': typeof AppMaisRoute
  '/relatorios': typeof AppRelatoriosRoute
  '/clientes/novo': typeof AppClientesNovoRoute
  '/colaboradores/$id': typeof AppColaboradoresIdRouteWithChildren
  '/colaboradores/novo': typeof AppColaboradoresNovoRoute
  '/ordens/$id': typeof AppOrdensIdRouteWithChildren
  '/ordens/nova': typeof AppOrdensNovaRoute
  '/relatorios/imprimir': typeof AppRelatoriosImprimirRoute
  '/clientes': typeof AppClientesIndexRoute
  '/colaboradores': typeof AppColaboradoresIndexRoute
  '/ordens': typeof AppOrdensIndexRoute
  '/clientes/$id/editar': typeof AppClientesIdEditarRoute
  '/colaboradores/$id/editar': typeof AppColaboradoresIdEditarRoute
  '/colaboradores/$id/horas': typeof AppColaboradoresIdHorasRoute
  '/colaboradores/$id/ordens': typeof AppColaboradoresIdOrdensRoute
  '/colaboradores/$id/precificacao': typeof AppColaboradoresIdPrecificacaoRoute
  '/ordens/$id/imprimir': typeof AppOrdensIdImprimirRoute
  '/relatorios/cliente/$clientId': typeof AppRelatoriosClienteClientIdRoute
  '/lovable/email/queue/process': typeof LovableEmailQueueProcessRoute
  '/clientes/$id': typeof AppClientesIdIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_app': typeof AppRouteWithChildren
  '/login': typeof LoginRoute
  '/_app/clientes': typeof AppClientesRouteWithChildren
  '/_app/colaboradores': typeof AppColaboradoresRouteWithChildren
  '/_app/dashboard': typeof AppDashboardRoute
  '/_app/mais': typeof AppMaisRoute
  '/_app/relatorios': typeof AppRelatoriosRoute
  '/_app/clientes/novo': typeof AppClientesNovoRoute
  '/_app/colaboradores/$id': typeof AppColaboradoresIdRouteWithChildren
  '/_app/colaboradores/novo': typeof AppColaboradoresNovoRoute
  '/_app/ordens/$id': typeof AppOrdensIdRouteWithChildren
  '/_app/ordens/nova': typeof AppOrdensNovaRoute
  '/_app/relatorios_/imprimir': typeof AppRelatoriosImprimirRoute
  '/_app/clientes/': typeof AppClientesIndexRoute
  '/_app/colaboradores/': typeof AppColaboradoresIndexRoute
  '/_app/ordens/': typeof AppOrdensIndexRoute
  '/_app/clientes/$id/editar': typeof AppClientesIdEditarRoute
  '/_app/colaboradores/$id/editar': typeof AppColaboradoresIdEditarRoute
  '/_app/colaboradores/$id/horas': typeof AppColaboradoresIdHorasRoute
  '/_app/colaboradores/$id/ordens': typeof AppColaboradoresIdOrdensRoute
  '/_app/colaboradores/$id/precificacao': typeof AppColaboradoresIdPrecificacaoRoute
  '/_app/ordens/$id/imprimir': typeof AppOrdensIdImprimirRoute
  '/_app/relatorios_/cliente/$clientId': typeof AppRelatoriosClienteClientIdRoute
  '/lovable/email/queue/process': typeof LovableEmailQueueProcessRoute
  '/_app/clientes/$id/': typeof AppClientesIdIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/clientes'
    | '/colaboradores'
    | '/dashboard'
    | '/mais'
    | '/relatorios'
    | '/clientes/novo'
    | '/colaboradores/$id'
    | '/colaboradores/novo'
    | '/ordens/$id'
    | '/ordens/nova'
    | '/relatorios/imprimir'
    | '/clientes/'
    | '/colaboradores/'
    | '/ordens/'
    | '/clientes/$id/editar'
    | '/colaboradores/$id/editar'
    | '/colaboradores/$id/horas'
    | '/colaboradores/$id/ordens'
    | '/colaboradores/$id/precificacao'
    | '/ordens/$id/imprimir'
    | '/relatorios/cliente/$clientId'
    | '/lovable/email/queue/process'
    | '/clientes/$id/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/dashboard'
    | '/mais'
    | '/relatorios'
    | '/clientes/novo'
    | '/colaboradores/$id'
    | '/colaboradores/novo'
    | '/ordens/$id'
    | '/ordens/nova'
    | '/relatorios/imprimir'
    | '/clientes'
    | '/colaboradores'
    | '/ordens'
    | '/clientes/$id/editar'
    | '/colaboradores/$id/editar'
    | '/colaboradores/$id/horas'
    | '/colaboradores/$id/ordens'
    | '/colaboradores/$id/precificacao'
    | '/ordens/$id/imprimir'
    | '/relatorios/cliente/$clientId'
    | '/lovable/email/queue/process'
    | '/clientes/$id'
  id:
    | '__root__'
    | '/'
    | '/_app'
    | '/login'
    | '/_app/clientes'
    | '/_app/colaboradores'
    | '/_app/dashboard'
    | '/_app/mais'
    | '/_app/relatorios'
    | '/_app/clientes/novo'
    | '/_app/colaboradores/$id'
    | '/_app/colaboradores/novo'
    | '/_app/ordens/$id'
    | '/_app/ordens/nova'
    | '/_app/relatorios_/imprimir'
    | '/_app/clientes/'
    | '/_app/colaboradores/'
    | '/_app/ordens/'
    | '/_app/clientes/$id/editar'
    | '/_app/colaboradores/$id/editar'
    | '/_app/colaboradores/$id/horas'
    | '/_app/colaboradores/$id/ordens'
    | '/_app/colaboradores/$id/precificacao'
    | '/_app/ordens/$id/imprimir'
    | '/_app/relatorios_/cliente/$clientId'
    | '/lovable/email/queue/process'
    | '/_app/clientes/$id/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRoute: typeof AppRouteWithChildren
  LoginRoute: typeof LoginRoute
  LovableEmailQueueProcessRoute: typeof LovableEmailQueueProcessRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/relatorios': {
      id: '/_app/relatorios'
      path: '/relatorios'
      fullPath: '/relatorios'
      preLoaderRoute: typeof AppRelatoriosRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/mais': {
      id: '/_app/mais'
      path: '/mais'
      fullPath: '/mais'
      preLoaderRoute: typeof AppMaisRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/dashboard': {
      id: '/_app/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AppDashboardRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/colaboradores': {
      id: '/_app/colaboradores'
      path: '/colaboradores'
      fullPath: '/colaboradores'
      preLoaderRoute: typeof AppColaboradoresRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/clientes': {
      id: '/_app/clientes'
      path: '/clientes'
      fullPath: '/clientes'
      preLoaderRoute: typeof AppClientesRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/ordens/': {
      id: '/_app/ordens/'
      path: '/ordens'
      fullPath: '/ordens/'
      preLoaderRoute: typeof AppOrdensIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/colaboradores/': {
      id: '/_app/colaboradores/'
      path: '/'
      fullPath: '/colaboradores/'
      preLoaderRoute: typeof AppColaboradoresIndexRouteImport
      parentRoute: typeof AppColaboradoresRoute
    }
    '/_app/clientes/': {
      id: '/_app/clientes/'
      path: '/'
      fullPath: '/clientes/'
      preLoaderRoute: typeof AppClientesIndexRouteImport
      parentRoute: typeof AppClientesRoute
    }
    '/_app/relatorios_/imprimir': {
      id: '/_app/relatorios_/imprimir'
      path: '/relatorios/imprimir'
      fullPath: '/relatorios/imprimir'
      preLoaderRoute: typeof AppRelatoriosImprimirRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/ordens/nova': {
      id: '/_app/ordens/nova'
      path: '/ordens/nova'
      fullPath: '/ordens/nova'
      preLoaderRoute: typeof AppOrdensNovaRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/ordens/$id': {
      id: '/_app/ordens/$id'
      path: '/ordens/$id'
      fullPath: '/ordens/$id'
      preLoaderRoute: typeof AppOrdensIdRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/colaboradores/novo': {
      id: '/_app/colaboradores/novo'
      path: '/novo'
      fullPath: '/colaboradores/novo'
      preLoaderRoute: typeof AppColaboradoresNovoRouteImport
      parentRoute: typeof AppColaboradoresRoute
    }
    '/_app/colaboradores/$id': {
      id: '/_app/colaboradores/$id'
      path: '/$id'
      fullPath: '/colaboradores/$id'
      preLoaderRoute: typeof AppColaboradoresIdRouteImport
      parentRoute: typeof AppColaboradoresRoute
    }
    '/_app/clientes/novo': {
      id: '/_app/clientes/novo'
      path: '/novo'
      fullPath: '/clientes/novo'
      preLoaderRoute: typeof AppClientesNovoRouteImport
      parentRoute: typeof AppClientesRoute
    }
    '/_app/clientes/$id/': {
      id: '/_app/clientes/$id/'
      path: '/$id'
      fullPath: '/clientes/$id/'
      preLoaderRoute: typeof AppClientesIdIndexRouteImport
      parentRoute: typeof AppClientesRoute
    }
    '/lovable/email/queue/process': {
      id: '/lovable/email/queue/process'
      path: '/lovable/email/queue/process'
      fullPath: '/lovable/email/queue/process'
      preLoaderRoute: typeof LovableEmailQueueProcessRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/relatorios_/cliente/$clientId': {
      id: '/_app/relatorios_/cliente/$clientId'
      path: '/relatorios/cliente/$clientId'
      fullPath: '/relatorios/cliente/$clientId'
      preLoaderRoute: typeof AppRelatoriosClienteClientIdRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/ordens/$id/imprimir': {
      id: '/_app/ordens/$id/imprimir'
      path: '/imprimir'
      fullPath: '/ordens/$id/imprimir'
      preLoaderRoute: typeof AppOrdensIdImprimirRouteImport
      parentRoute: typeof AppOrdensIdRoute
    }
    '/_app/colaboradores/$id/precificacao': {
      id: '/_app/colaboradores/$id/precificacao'
      path: '/precificacao'
      fullPath: '/colaboradores/$id/precificacao'
      preLoaderRoute: typeof AppColaboradoresIdPrecificacaoRouteImport
      parentRoute: typeof AppColaboradoresIdRoute
    }
    '/_app/colaboradores/$id/ordens': {
      id: '/_app/colaboradores/$id/ordens'
      path: '/ordens'
      fullPath: '/colaboradores/$id/ordens'
      preLoaderRoute: typeof AppColaboradoresIdOrdensRouteImport
      parentRoute: typeof AppColaboradoresIdRoute
    }
    '/_app/colaboradores/$id/horas': {
      id: '/_app/colaboradores/$id/horas'
      path: '/horas'
      fullPath: '/colaboradores/$id/horas'
      preLoaderRoute: typeof AppColaboradoresIdHorasRouteImport
      parentRoute: typeof AppColaboradoresIdRoute
    }
    '/_app/colaboradores/$id/editar': {
      id: '/_app/colaboradores/$id/editar'
      path: '/editar'
      fullPath: '/colaboradores/$id/editar'
      preLoaderRoute: typeof AppColaboradoresIdEditarRouteImport
      parentRoute: typeof AppColaboradoresIdRoute
    }
    '/_app/clientes/$id/editar': {
      id: '/_app/clientes/$id/editar'
      path: '/$id/editar'
      fullPath: '/clientes/$id/editar'
      preLoaderRoute: typeof AppClientesIdEditarRouteImport
      parentRoute: typeof AppClientesRoute
    }
  }
}

interface AppClientesRouteChildren {
  AppClientesNovoRoute: typeof AppClientesNovoRoute
  AppClientesIndexRoute: typeof AppClientesIndexRoute
  AppClientesIdEditarRoute: typeof AppClientesIdEditarRoute
  AppClientesIdIndexRoute: typeof AppClientesIdIndexRoute
}

const AppClientesRouteChildren: AppClientesRouteChildren = {
  AppClientesNovoRoute: AppClientesNovoRoute,
  AppClientesIndexRoute: AppClientesIndexRoute,
  AppClientesIdEditarRoute: AppClientesIdEditarRoute,
  AppClientesIdIndexRoute: AppClientesIdIndexRoute,
}

const AppClientesRouteWithChildren = AppClientesRoute._addFileChildren(
  AppClientesRouteChildren,
)

interface AppColaboradoresIdRouteChildren {
  AppColaboradoresIdEditarRoute: typeof AppColaboradoresIdEditarRoute
  AppColaboradoresIdHorasRoute: typeof AppColaboradoresIdHorasRoute
  AppColaboradoresIdOrdensRoute: typeof AppColaboradoresIdOrdensRoute
  AppColaboradoresIdPrecificacaoRoute: typeof AppColaboradoresIdPrecificacaoRoute
}

const AppColaboradoresIdRouteChildren: AppColaboradoresIdRouteChildren = {
  AppColaboradoresIdEditarRoute: AppColaboradoresIdEditarRoute,
  AppColaboradoresIdHorasRoute: AppColaboradoresIdHorasRoute,
  AppColaboradoresIdOrdensRoute: AppColaboradoresIdOrdensRoute,
  AppColaboradoresIdPrecificacaoRoute: AppColaboradoresIdPrecificacaoRoute,
}

const AppColaboradoresIdRouteWithChildren =
  AppColaboradoresIdRoute._addFileChildren(AppColaboradoresIdRouteChildren)

interface AppColaboradoresRouteChildren {
  AppColaboradoresIdRoute: typeof AppColaboradoresIdRouteWithChildren
  AppColaboradoresNovoRoute: typeof AppColaboradoresNovoRoute
  AppColaboradoresIndexRoute: typeof AppColaboradoresIndexRoute
}

const AppColaboradoresRouteChildren: AppColaboradoresRouteChildren = {
  AppColaboradoresIdRoute: AppColaboradoresIdRouteWithChildren,
  AppColaboradoresNovoRoute: AppColaboradoresNovoRoute,
  AppColaboradoresIndexRoute: AppColaboradoresIndexRoute,
}

const AppColaboradoresRouteWithChildren =
  AppColaboradoresRoute._addFileChildren(AppColaboradoresRouteChildren)

interface AppOrdensIdRouteChildren {
  AppOrdensIdImprimirRoute: typeof AppOrdensIdImprimirRoute
}

const AppOrdensIdRouteChildren: AppOrdensIdRouteChildren = {
  AppOrdensIdImprimirRoute: AppOrdensIdImprimirRoute,
}

const AppOrdensIdRouteWithChildren = AppOrdensIdRoute._addFileChildren(
  AppOrdensIdRouteChildren,
)

interface AppRouteChildren {
  AppClientesRoute: typeof AppClientesRouteWithChildren
  AppColaboradoresRoute: typeof AppColaboradoresRouteWithChildren
  AppDashboardRoute: typeof AppDashboardRoute
  AppMaisRoute: typeof AppMaisRoute
  AppRelatoriosRoute: typeof AppRelatoriosRoute
  AppOrdensIdRoute: typeof AppOrdensIdRouteWithChildren
  AppOrdensNovaRoute: typeof AppOrdensNovaRoute
  AppRelatoriosImprimirRoute: typeof AppRelatoriosImprimirRoute
  AppOrdensIndexRoute: typeof AppOrdensIndexRoute
  AppRelatoriosClienteClientIdRoute: typeof AppRelatoriosClienteClientIdRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppClientesRoute: AppClientesRouteWithChildren,
  AppColaboradoresRoute: AppColaboradoresRouteWithChildren,
  AppDashboardRoute: AppDashboardRoute,
  AppMaisRoute: AppMaisRoute,
  AppRelatoriosRoute: AppRelatoriosRoute,
  AppOrdensIdRoute: AppOrdensIdRouteWithChildren,
  AppOrdensNovaRoute: AppOrdensNovaRoute,
  AppRelatoriosImprimirRoute: AppRelatoriosImprimirRoute,
  AppOrdensIndexRoute: AppOrdensIndexRoute,
  AppRelatoriosClienteClientIdRoute: AppRelatoriosClienteClientIdRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRoute: AppRouteWithChildren,
  LoginRoute: LoginRoute,
  LovableEmailQueueProcessRoute: LovableEmailQueueProcessRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
